### ISSUE TITLE
Refactor flowdock-utils lib file to clean up inconsistent naming

### ISSUE THREAD

**Issue by kb0rg** [thesis/valkyrie#104]
See [conversation](https://github.com/thesis/heimdall/pull/97#discussion_r313598662) in PR 97 
and [another note](https://github.com/thesis/heimdall/pull/102#discussion_r314089196) in PR 102

**Comment by Shadowfiend** [comment]
Closing this for now. Without flowdock, a lot of this has gotten phased out. The remaining adapter utils represent things we should probably implement as first-class hubot citizens in the https://github.com/thesis/hubot fork.
