### ISSUE TITLE
Add a package to measure test coverage

### ISSUE THREAD

**Issue by kb0rg** [thesis/valkyrie#114]
Once we've established a baseline for creating and running tests for Heimdall (epics #99 and #113 ), we should begin to enforce coverage for any new code.

TODO: 
Discuss/ clarify expectations here.
(eg: Test coverage reports can be via git hook (maybe?), and merges should be prohibited with missing tests (also maybe).)

**Comment by Shadowfiend** [comment]
Closing this for now. Someday maybe we want to do this, but it's not at the top of the list.
