### ISSUE TITLE
Save user timezone preference, use it to set timezone for reminder set by user

### ISSUE THREAD

**Issue by kb0rg** [thesis/valkyrie#140]
We should save a user preferences object to the robot brain, and use it to store users' timezone preferences.

We will need to implement commands to update or edit this (eg when traveling), possibly consider a "default" as well as optional "current" timezone field.

The remind command should check whether this preference is set for the user initiating the remind command, and if so, use the relevant timezone (if no other tz is specified in the request) to create and display the reminder job. 

See [conversation here](https://www.flowdock.com/app/cardforcoin/bifrost/threads/ZwFq5vy-wJIb_NJBq45xVgkt4GX
) for additional context.

**Comment by Shadowfiend** [comment]
Closed by #237.
