### ISSUE TITLE
Update Heimdall CircleCi integration to use orbs

### ISSUE THREAD

**Issue by kb0rg** [thesis/valkyrie#156]
The circle-flowdock integration we currently use is deprecated, and there is no longer a way to edit the settings in circle.

A [conversation with circle support](https://www.flowdock.com/app/cardforcoin/bifrost/threads/spYCqUY9YHqk5eAwak2y4P_zCaU) recommends that we switch to using [orbs](https://circleci.com/docs/2.0/creating-orbs/)

At the moment there is no date by which we have to do this, but the flowdock thread referenced above will receive updates.

Note: 
We should update our Sentry integration as well -- it's also using the deprecated Flowdock push API. However, at the moment we still have access to [Sentry's legacy integration settings](https://sentry.io/settings/card-for-coin-inc/projects/cfc/plugins/).

**Comment by Shadowfiend** [comment]
Closing as we've moved to GitHub Actions and Element.
